### ISSUE TITLE
Mercy White Stable

### ISSUE THREAD

**Issue by BornWithGuns** [Hexer-7/Overwatch-Mercy-AI#1]
Get this when I try to start it. The other version works fine just the white version. Using 1080, 7 as dmg, and 6 as heal

Traceback (most recent call last):
  File "D:\Downloads\Overwatch-Mercy-AI-Mercy.AI.v1.2.1.WE\Overwatch-Mercy-AI-Mercy.AI.v1.2.1.WE\Mercy AI 1.2.1 White Edition.py", line 268, in <module>
    capture_screen(f'data/{selected_resolution}/white.png')
  File "D:\Downloads\Overwatch-Mercy-AI-Mercy.AI.v1.2.1.WE\Overwatch-Mercy-AI-Mercy.AI.v1.2.1.WE\Mercy AI 1.2.1 White Edition.py", line 165, in capture_screen
    reference_image = filter_color(reference_image)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\Overwatch-Mercy-AI-Mercy.AI.v1.2.1.WE\Overwatch-Mercy-AI-Mercy.AI.v1.2.1.WE\Mercy AI 1.2.1 White Edition.py", line 145, in filter_color
    image = cv2.bitwise_and(image, image, mask=image_mask)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:230: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'cv::binary_op'

**Comment by Hexer-7** [comment]
What resolution do you use?

**Comment by Hexer-7** [comment]
Hi, my friend 

the issue has been fixed in the latest update (version 1.2.2).

I made a mistake by testing the code only on a 2K screen resolution and not checking other resolutions. I realize this might have caused some inconvenience, and I apologize for any frustration.

If you have more feedback or suggestions, feel free to share. Your input is valuable.

Thanks.
